install:
  - choco install winscp
  - choco install hugo

environment:
  relative_local_directory: ..\public
  remote_directory: /private_html
  ftp_host: ducode.org
  ftp_username:
    secure: 2m0LRawKxFr6rsAdgiehNQ==
  ftp_password:
    secure: 6g36EHlTaBrJQIoEm1L81DIoHdmJNh1TjPdjox/OdT8=

artifacts:
  - path: public
    name: ducode
    type: zip

branches:
  only:
    - master

build_script:
  - git submodule update --init --recursive
  - ps: scripts\build.ps1

deploy_script:
  - ps: scripts\deploy.ps1

test: off