baseURL = "https://ducode.org/"
languageCode = "en-us"
title = "Ducode"
theme = "ananke"
pluralizeListTitles = false

[params]
  description = "About programming and about everything else"

[[menu.main]]
    name = "KB"
    identifier = "knowledgebase"
    url = "/knowledgebase/"